# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=15000),
        ),
        migrations.AlterField(
            model_name='post',
            name='introduction',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
