# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_publication_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publication_datetime',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=15000, validators=[posts.validators.badwords]),
        ),
        migrations.AlterField(
            model_name='post',
            name='introduction',
            field=models.TextField(max_length=150, validators=[posts.validators.badwords]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=150, validators=[posts.validators.badwords]),
        ),
    ]
