# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publication_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='publication_date',
            field=models.DateField(),
        ),
    ]
