# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Blogs',
        ),
    ]
